urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.conf import settings
from mezzanine.core.views import direct_to_template

from customizations.views import HomepageView


admin.autodiscover()
urlpatterns = i18n_patterns(
    "",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

urlpatterns += patterns(
    '',
    url(r"^$", direct_to_template, {"template": "splash.html"}, name="home"),
    # url(r'^$', HomepageView.as_view(), name='home'),
    url(r'^ckeditor/', include('ckeditor.urls')),

    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    (r"^", include("customizations.urls")),

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

if settings.DEBUG:
    urlpatterns = patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns

veldthollow/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.http import HttpResponse

from mezzanine.conf import settings
from mezzanine.core.sitemaps import DisplayableSitemap

from .views import (
    AuthorArticleListView,
    AuthorListView,
    BlogRouterView,
    HomepageView,
)


admin.autodiscover()
urlpatterns = i18n_patterns(
    "",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
)

urlpatterns += patterns(
    '',
    url(r'^$', HomepageView.as_view(), name='home'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # ADD YOUR OWN URLPATTERNS HERE.
)
# Return a robots.txt that disallows all spiders when DEBUG is True.
if getattr(settings, 'DEBUG', False):
    urlpatterns += patterns(
        '',
        url('^robots.txt$',
            lambda r: HttpResponse('User-agent: *\nDisallow: /',
                                   content_type='text/plain')),
    )

urlpatterns += patterns(
    '',
    url(r'^jsi18n/(?P<packages>\S+?)/$',
        'django.views.i18n.javascript_catalog', {'domain': 'django'}),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'all': DisplayableSitemap}}),
    url(r'^', include('mezzanine.core.urls')),
    url(r'^', include('mezzanine.generic.urls')),
)

# Blog urls
urlpatterns += patterns(
    'mezzanine.blog.views',
    url("^$", "blog_post_list", name="blog_post_list"),
    url('^feed.(?P<format>(rss|atom))$', 'blog_post_feed',
        name='blog_post_feed'),
    url('^(?P<category>.*).(?P<format>(rss|atom))$', 'blog_post_feed',
        name='blog_post_feed_category'),
    url("^authors/$", AuthorListView.as_view(),
        name="blog_post_authors",
        kwargs={'template': 'blog/blog_post_list_authors.html'}),
    url("^authors/(?P<author>.*)/$", AuthorArticleListView.as_view(),
        name="blog_post_list_author",
        kwargs={'template': 'blog/blog_post_list_authors.html'}),
    url(r'^(?P<slug>.*)/$', BlogRouterView.as_view()),
    url('^(?P<category>.*)/$', 'blog_post_list',
        name='blog_post_list_category'),
    url('^(?P<slug>.*)/$', 'blog_post_detail',
        name='blog_post_detail'),
)

urlpatterns += patterns(
    '',
    url(r'^', include('mezzanine.pages.urls')),
)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

if settings.DEBUG:
    urlpatterns = patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns

veldthollow/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import SmartResize
from mezzanine.blog.models import BlogCategory
from mezzanine.core.fields import RichTextField
from mezzanine.pages.models import Page
from mezzanine.utils.models import upload_to

from .fields import FileBrowseImageField


class User(AbstractUser):
    contact_email = models.EmailField(blank=True)
    NONAUTHOR = None
    GUEST = 5
    STAFF = 10
    AUTHOR_STATUS_CHOICES = (
        (NONAUTHOR, 'No'),
        (GUEST, 'Guest'),
        (STAFF, 'Staff'),
    )
    author_status = models.IntegerField(
        'Author Status', choices=AUTHOR_STATUS_CHOICES, default=None, null=True)
    short_bio = models.TextField(blank=True)
    full_bio = RichTextField(blank=True)
    profile_image = FileBrowseImageField(
        file_obj_name='profile_image_file',
        upload_to=upload_to("veldthollow.User.profile_image", "profiles"),
        format="Image", max_length=255, null=True, blank=True)
    profile_thumbnail = ImageSpecField(
        source='profile_image_file', processors=[SmartResize(150, 150)],
        format='PNG')

    USERNAME_FIELD = 'username'

    class Meta:
        db_table = 'auth_user'
        ordering = ('first_name', 'last_name')

    def __str__(self):
        return self.get_full_name() or self.username


class AuthorLink(models.Model):
    user = models.ForeignKey(User)
    LINK_TYPE_CHOICES = (
        ('facebook', 'Facebook'),
        ('twitter', 'Twitter'),
        ('instagram', 'Instagram'),
        ('web', 'Web'),
        ('pinterest', 'Pinterest'),
    )
    link_type = models.CharField(max_length=25, choices=LINK_TYPE_CHOICES)
    url = models.URLField()


class Homepage(Page):
    featured_category = models.ForeignKey(
        BlogCategory, blank=True, null=True)
    featured_author = models.ForeignKey(User, blank=True, null=True)

templates/blog/author_profile.html
{% overextends "blog/blog_post_list.html" %}
{% load i18n future mezzanine_tags blog_tags keyword_tags disqus_tags %}

{% block body_id %}author_article_list{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            
            <div class="author-header row">
                <h1 class="col-xs-12 visible-xs-block">{{ author.get_full_name|default:author.username }}</h1>
                <div class="col-sm-3 col-xs-5"><img class="img-responsive img-circle" src="{{MEDIA_URL}}{% thumbnail author.profile_image 255 255 %}" /></div>
                <div class="author-info col-sm-9 col-xs-7">
                    <h1 class="hidden-xs">{{ author.get_full_name|default:author.username }}</h1>
                    {% if author.authorlink_set.exists %}
                    <ul class="author_links list-inline">
                        {% for link in author.authorlink_set.all %}
                        <li class="author_link"><a href="{{link.url}}" target="_blank"><i class="fa fa-{% if link.link_type == 'web' %}globe{% else %}{{link.link_type}}{% endif %}"></i></a></li>
                        {% endfor %}
                        {% if author.contact_email %}
                        <li class="author_link"><a href="mailto:{{author.contact_email}}">Contact {{author.get_full_name}}</a></li>
                        {% endif %}
                    </ul>
                    {% endif %}
                </div>
                <div class="clearfix"></div>
                <p class="author_bio col-xs-12">{{author.full_bio|safe}}</p>
            </div>

        </div>
        <article class="col-md-12">
            <div class="row">
                <h3 class="col-xs-12">{{author.get_full_name}}'s collection on work</h3>
                {% for article in blog_posts %}
                <div class="post col-md-3">
                    <figure>
                    {% if article.featured_image %}
                    <a href="{{ article.get_absolute_url }}">
                        <img class="img-thumbnail" src="{{ MEDIA_URL }}{% thumbnail article.featured_image 270 0 %}">
                    </a>
                    {% endif %}
                    <h4><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h4>
                    </figure>
                </div>
                {% endfor %}

                {% pagination_for paginator %}
            </div>
        </article>
    </div>
</div>
{% endblock %}

templates/blog/authors.html
{% overextends "blog/blog_post_list.html" %}
{% load i18n future mezzanine_tags blog_tags keyword_tags disqus_tags %}

{% block body_id %}author_list{% endblock %}

{% block main %}
<div class="container">
    <article class="row">
        <div class="col-md-12">
            <div class="author-list-header">
                <h1>{{request.page.title}}</h1>
                {{request.page.get_content_model.content|safe}}
            </div>
            <h2>Staff Writers</h2>
            {% for author in staff %}
            <div class="author-header row">
                <div class="col-md-3 col-sm-4 col-xs-5">
                    <img class="img-responsive img-circle" src="{{MEDIA_URL}}{% thumbnail author.profile_image 290 290 %}" />
                    <h3 class="hidden-xs text-center">{{ author.get_full_name|default:author.username }}</h3>
                </div>
                <h3 class="visible-xs col-xs-7">{{ author.get_full_name|default:author.username }}</h3>
                <p class="author_bio hidden-xs">{{author.short_bio|safe}}</p>
                {% if author.authorlink_set.exists %}
                <ul class="author_links list-inline col-md-9 col-sm-8 col-xs-7">
                    {% for link in author.authorlink_set.all %}
                    <li class="author_link"><a href="{{link.url}}" target="_blank"><i class="fa fa-{% if link.link_type == 'web' %}globe{% else %}{{link.link_type}}{% endif %}"></i></a></li>
                    {% endfor %}
                    {% if author.contact_email %}
                    <li class="author_link"><a href="mailto:{{author.contact_email}}">Contact {{author.get_full_name}}</a></li>
                    {% endif %}
                </ul>
                {% endif %}
                <div class="clearfix"></div>
                <p class="author_bio visible-xs col-xs-12">{{author.short_bio|safe}}</p>
            </div>
            {% endfor %}
        </div>
        {% if guests %}
        <h2>Guest Writers</h2>
        {% for author in guests %}
        <div class="col-sm-6 row">
            <img class="img-responsive img-circle col-xs-4" src="{{MEDIA_URL}}{% thumbnail author.profile_image 290 290 %}" />
            <h3 class="col-xs-8">{{ author.get_full_name|default:author.username }}</h3>
            {% if author.authorlink_set.exists %}
            <ul class="author_links list-inline col-xs-8">
                {% for link in author.authorlink_set.all %}
                <li class="author_link"><a href="{{link.url}}" target="_blank"><i class="fa fa-{% if link.link_type == 'web' %}globe{% else %}{{link.link_type}}{% endif %}"></i></a></li>
                {% endfor %}
                {% if author.contact_email %}
                <li class="author_link"><a href="mailto:{{author.contact_email}}">Contact {{author.get_full_name}}</a></li>
                {% endif %}
            </ul>
            {% endif %}
            <div class="clearfix"></div>
            <p class="author_bio col-xs-12">{{author.short_bio|safe}}</p>
        </div>
        {% endfor %}
        {% endif %}
    </article>
</div>
{% endblock %}

templates/blog/blog_post_detail.html
{% overextends "blog/blog_post_detail.html" %}
{% load mezzanine_tags comment_tags keyword_tags rating_tags i18n future disqus_tags %}

{% block body_id %}article_page{% endblock %}

{% block main %}
<div class="container" itemscope itemtype="http://schema.org/Article">
    <div class="row">
        <header class="col-md-12">
            {% editable blog_post.title blog_post._meta_title blog_post.description %}
            <h1 class="headline" itemprop="headline">{{ blog_post.title }}</h1>
            {% endeditable %}
            <h2><time datetime="{{pub_date|date:"c"}}" itemprop="datePublished" content="{{pub_date|date:"c"}}">{{blog_post.publish_date|date:"F j, Y"}}</time></h2>
        </header>
        <div class="col-md-12">
            {% block blog_post_detail_featured_image %}
            {% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}
            <img class="img-responsive" src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 1140 0 %}">
            {% endif %}
            {% endblock %}
        </div>
        <article class="col-md-8">
            {% block blog_post_list_post_metainfo %}
                {% editable blog_post.user blog_post.publish_date blog_post.expiry_date blog_post.categories blog_post.keywords blog_post.in_sitemap %}
                <div class="categories">
                    {% with blog_post.categories.all as categories %}
                        {% if categories %}
                            {% for category in categories %}
                                <a itemprop="articleSection" href="{% url "blog_post_list_category" category.slug %}">{{ category }}</a>{% if not forloop.last %} | {% endif %}
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </div>
                <div class="author" itemscope itemprop="author" itemtype="http://schema.org/Person">
                    {% with blog_post.user as author %}
                        <a itemprop="name" href="{% url "blog_post_list_author" author %}">{{ author.get_full_name|default:author.username }}</a>
                    {% endwith %}
                </h6>
                {% endeditable %}
            {% endblock %}
            <div class="post" itemprop="articleBody">
                {% block blog_post_detail_content %}
                {% editable blog_post.content %}
                {{ blog_post.content|richtext_filters|safe }}
                {% endeditable %}
                {% endblock %}
                {% keywords_for blog_post as tags %}
                {% if tags %}
                    <ul class="list-inline tags">
                        <li>{% trans "Tags" %}:</li>
                        {% spaceless %}
                            {% for tag in tags %}
                                <li><a href="{% url "blog_post_list_tag" tag.slug %}">{{ tag }}</a></li>
                            {% endfor %}
                        {% endspaceless %}
                    </ul>
                {% endif %}
            </div>
            {% with blog_post.user as author %}
            {% if blog_post.user %}
            <div class="author-bio row">
                <figure class="col-md-5">
                    <img src="{{MEDIA_URL}}{% thumbnail author.profile_image 150 150 %}" />
                    <figcaption>{{author.get_full_name|default:author.username}}</figcaption>
                </figure>
                <div class="bio col-md-7">
                    {{author.short_bio|richtext_filters|safe}}
                    <nav class="social-icons">
                        {% for link in author.authorlink_set.all %}
                        <a href="{{link.url}}" target="_blank"><i class="fa fa-{{link.link_type}}"></i></a>
                        {% endfor %}
                    </nav>
                </div>
            </div>
            {% endif %}
            {% endwith %}
                 
        </article>
        <aside class="col-md-4">
            {% block blog_post_detail_related_posts %}
            <div class="ad">ADS GO RIGHT HERE</div>
            {#% editable blog_post.related_posts %#}
            {% if blog_post.related_posts.published %}
            <div id="related-posts">
                <h4>Related Articles</h4>
                {% for post in blog_post.related_posts.published %}
                <div class="related-post">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {#% endeditable %#}
            <div class="ad">ADS GO RIGHT HERE</div>
            {% endblock %}
        </aside>
    </div>
</div>
<section class="comments">
    <div class="container">
        <div class="row">
                {% block blog_post_detail_commentlink %}
                <p>
                    {% editable blog_post.allow_comments %}
                    {% if blog_post.allow_comments %}
                        {% if settings.COMMENTS_DISQUS_SHORTNAME %}
                            (<a href="{{ blog_post.get_absolute_url }}#disqus_thread"
                                data-disqus-identifier="{% disqus_id_for blog_post %}">{% spaceless %}
                                {% trans "Comments" %}
                            {% endspaceless %}</a>)
                        {% else %}(<a href="#comments">{% spaceless %}
                            {% blocktrans count comments_count=blog_post.comments_count %}{{ comments_count }} comment{% plural %}{{ comments_count }} comments{% endblocktrans %}
                            {% endspaceless %}</a>)
                        {% endif %}
                    {% endif %}
                    {% endeditable %}
                </p>
                {% endblock %}
                {% if settings.COMMENTS_DISQUS_SHORTNAME %}
                {% include "generic/includes/disqus_counts.html" %}
                {% endif %}
                {% block blog_post_detail_rating %}{% endblock %}
                {% block blog_post_detail_sharebuttons %}
                    {% set_short_url_for blog_post %}
                    <a class="btn btn-sm share-twitter" target="_blank" href="http://twitter.com/home?status={{ blog_post.short_url|urlencode }}%20{{ blog_post.title|urlencode }}">{% trans "Share on Twitter" %}</a>
                    <a class="btn btn-sm share-facebook" target="_blank" href="http://facebook.com/sharer.php?u={{ request.build_absolute_uri }}&amp;t={{ blog_post.title|urlencode }}">{% trans "Share on Facebook" %}</a>
                {% endblock %}

                {% block blog_post_previous_next %}
                {% endblock %}

                {% block blog_post_detail_comments %}
                {% if blog_post.allow_comments %}{% comments_for blog_post %}{% endif %}
                {% endblock %}
        </div>
    </div>
</section>
{% endblock %}

templates/blog/blog_post_list.html
{% overextends "blog/blog_post_list.html" %}
{% load i18n future mezzanine_tags blog_tags keyword_tags disqus_tags %}

{% block body_id %}page_blog_list{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>
                {% if tag or category %}
                {% block blog_post_list_filterinfo %}
                {% if tag %}
                    {% trans "Viewing posts tagged" %} {{ tag }}
                {% else %}{% if category %}
                    {{ category }}
                {% endif %}{% endif %}
                {% endblock %}
                {% endif %}
            </h1>
        </div>
        <article class="col-md-9">
            <div class="row">
                {% for article in blog_posts.object_list %}
                    {% if forloop.first %}
                        <div class="post col-md-12">
                            {% if article.featured_image %}
                            <a href="{{ article.get_absolute_url }}">
                                <img class="img-responsive img-thumbnail" src="{{ MEDIA_URL }}{% thumbnail article.featured_image 850 380 %}">
                            </a>
                            {% endif %}
                            <h2><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h2>
                            <h3 class="author">by {{article.user.get_full_name}}</h3>
                        </div>
                    {% else %}
                        <div class="post col-md-6">
                            {% if article.featured_image %}
                            <a href="{{ article.get_absolute_url }}">
                                <img class="img-responsive img-thumbnail" src="{{ MEDIA_URL }}{% thumbnail article.featured_image 400 180 %}">
                            </a>
                            {% endif %}
                            <h4><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h4>
                            <h5 class="author">by {{article.user.get_full_name}}</h5>
                        </div>
                    {% endif %}
                {% endfor %}

                <div class="clearfix"></div>
                {% pagination_for blog_posts %}
            </div>
        </article>
        <aside class="col-md-3">
            <div class="ad">ADS GO RIGHT HERE</div>
            <div class="ad">ADS GO RIGHT HERE</div>
            {% include "includes/keyword_sidebar.html" %}
        </aside>
    </div>
</div>
{% endblock %}